#!/usr/bin/env python2

# Commandline tool

if __name__ == '__main__':

    import sys
    import webbrowser
    from facelib import run
    from config import server_address

    if '--help' in sys.argv or '-h' in sys.argv:
        print('''
    --help or =h to print this help
    --no-browser to not run web interface at {}:{}
    '''.format(*server_address))
        sys.exit()
    if '--no-browser' not in sys.argv:
        webbrowser.open('{}:{}'.format(*server_address))

    run()
