import os
import imp

HOME = os.path.expanduser("~")
DEFAULTCONFIGPATH = os.path.join(HOME, '.nayesdog')
default_config_file = DEFAULTCONFIGPATH+"/config.py"

default_config = """
from nayesdog.config import get_name_in_library, DEFAULTCONFIGPATH 

'''Default configuration file generated by NayseDog'''
feeds_url_dict = {
    'NatureResearch': 'http://feeds.nature.com/NatureLatestResearch',
    'Arstechnica': 'http://feeds.arstechnica.com/arstechnica/science',
    'Science': 'http://www.sciencemag.org/rss/current.xml',
} 
word_counts_database_file = DEFAULTCONFIGPATH + '/tables.py.gz'
previous_session_database_file = DEFAULTCONFIGPATH + '/previous_session'
maximal_number_of_entries_in_memory = 2000

server_address = ('127.0.0.1', 8081)
cssfile = get_name_in_library('css.css')
stopwords_file = get_name_in_library('stopwords.txt')
icons_folder = get_name_in_library("icons")
"""

def get_name_in_library(name, module_name="nayesdog"):
    library_location = imp.find_module(module_name)[1]
    return os.path.join(library_location, name)

def write_simple_config(file_name = default_config_file):
    if not os.path.isdir(DEFAULTCONFIGPATH):
        os.makedirs(DEFAULTCONFIGPATH)
    with open(file_name, "w") as f:
        f.write(default_config)

list_of_user_parameters = [
"server_address",
"cssfile",
"feeds_url_dict",
"word_counts_database_file",
"stopwords_file",
"previous_session_database_file",
"maximal_number_of_entries_in_memory",
"icons_folder"]

def make_me_config(file_path=None):
    if file_path is None:
        file_path = default_config_file
        if not os.path.isfile(default_config_file):
            write_simple_config()

    with open(file_path, 'r') as f:
        config = f.read()
        return config
