
'''Default configuration file generated by NayseDog'''
feeds_url_dict = {
    'NatureResearch': 'http://feeds.nature.com/NatureLatestResearch',
    'Arstechnica': 'http://feeds.arstechnica.com/arstechnica/science',
    'Science': 'http://www.sciencemag.org/rss/current.xml',
} 
word_counts_database_file = './tables.py.gz'
previous_session_database_file = '.previous_session'
maximal_number_of_entries_in_memory = 300
